name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 用 pnpm 时会报错 Error: Unable to locate executable file ... 
      # 解决办法 https://github.com/actions/setup-node/issues/530  https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
      - uses: pnpm/action-setup@v2
        with:
          version: 7.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
